version: '3.8'

services:
  server:
    build: .
    container_name: litestar
    depends_on:
      #- redis
      - postgres
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/mygpo-clone
      - SECRET_KEY=${SECRET_KEY}
      - REDIS_URL=${REDIS_URL}
    ports:
      - "8000:8000"
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mygpo-clone
    networks:
      - app-network
  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   networks:
  #     - app-network

volumes:
  #redis-data:
  postgres-data:


networks:
  app-network:
    driver: bridge
