@BASE_URL = http://0.0.0.0:8000

POST  {{BASE_URL}}/auth/register HTTP/1.1
Content-Type: application/x-www-form-urlencoded

&username=foo
&password=qNYWHa#LE,A(VS)%2/8g<p
&email=foo.foo@email.com


###
POST  {{BASE_URL}}/auth/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

&username=foo
&password=qNYWHa#LE,A(VS)%2/8g<p


###
POST  {{BASE_URL}}/auth/logout HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjUwNjE5OTksInN1YiI6ImNmN2M2ZjE3LTdlZGQtNGU5Mi04ZjM4LTE1MzgyNjBhNmU4ZCIsImlhdCI6MTcyNDk3NTU5OSwiZXh0cmFzIjp7ImVtYWlsIjoiZm9vLmZvb0BlbWFpbC5jb20ifX0.EBz69_t930Ma-rwit8dsRFGN72FDYLKiF_68srdyer8