// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: episodes_queries.sql

package database

import (
	"context"
	"time"
)

const getEpisodeByUrl = `-- name: GetEpisodeByUrl :one
SELECT
    title,
    url,
    podcast_title,
    podcast_url,
    description,
    website,
    released,
    mygpo_link
FROM
    episodes
where
    url = ?
`

type GetEpisodeByUrlRow struct {
	Title        string
	Url          string
	PodcastTitle string
	PodcastUrl   string
	Description  string
	Website      string
	Released     time.Time
	MygpoLink    string
}

func (q *Queries) GetEpisodeByUrl(ctx context.Context, url string) (GetEpisodeByUrlRow, error) {
	row := q.db.QueryRowContext(ctx, getEpisodeByUrl, url)
	var i GetEpisodeByUrlRow
	err := row.Scan(
		&i.Title,
		&i.Url,
		&i.PodcastTitle,
		&i.PodcastUrl,
		&i.Description,
		&i.Website,
		&i.Released,
		&i.MygpoLink,
	)
	return i, err
}
