// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
)

type Podcast struct {
	ID          int64
	Website     sql.NullString
	MygpoLink   sql.NullString
	Description string
	Subscribers int64
	Title       string
	Author      string
	Url         string
	LogoUrl     sql.NullString
}

type Tag struct {
	ID    int64
	Title string
	Code  string
	Usage int64
}

type User struct {
	ID       int64
	Username string
	Password string
	Email    string
}
