// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Episode struct {
	ID           int64
	Title        string
	Url          string
	PodcastTitle string
	PodcastUrl   string
	Description  string
	Website      string
	Released     time.Time
	MygpoLink    string
}

type Podcast struct {
	ID          int64
	Website     string
	MygpoLink   string
	Description string
	Subscribers int64
	Title       string
	Author      string
	Url         string
	LogoUrl     interface{}
}

type Tag struct {
	ID    int64
	Title string
	Code  string
	Usage int64
}

type User struct {
	ID       int64
	Username string
	Password string
	Email    string
}
