// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tag_queries.sql

package database

import (
	"context"
)

const topTags = `-- name: TopTags :many
SELECT title, code, usage FROM tags ORDER BY usage DESC LIMIT 10
`

type TopTagsRow struct {
	Title string
	Code  string
	Usage int64
}

func (q *Queries) TopTags(ctx context.Context) ([]TopTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, topTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopTagsRow
	for rows.Next() {
		var i TopTagsRow
		if err := rows.Scan(&i.Title, &i.Code, &i.Usage); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
